### PR TITLE
In form editor, After remove a form field I can undo this remove Fixed

### LINKED ISSUE #56: In form editor, After remove a form field I can undo this remove
when user is editing the form, he want to experiment with different fields, so we can allow him to restore a deleted field.

One approach:
In the form field, there is a remove icon button on the right side. We can replace that icon with the undo icon button. Clicking this undo icon button will restore the field.

### PR DESCRIPTION
**Pull request by Hemu21**
## Description
when user is editing the form, he want to experiment with different fields, so we can allow him to restore a deleted field. Now user can undo the deleted field. I had added the undo button If user click on delete then undo button will appear. 

## Issue
[Issue Link](https://github.com/growupanand/ConvoForm/issues/56) resolve #56

### CODE REVIEW

**Comment by Hemu21** [comment]
@growupanand  can you please check and merge it.

**Comment by growupanand** [comment]
@Hemu21 , lets improve the UX here, instead of removing the field immediatly from the UI, just show disabled field with undo icon button next to it, this will show user what are the fileds he has removed so he can easilly undo the field which he want.

After saving the form all the fields which are marked to remove should also removed from the UI.


**UI example**
image

**Comment by growupanand** [comment]
@Hemu21 make sure you have fixed all the type errors before commit the code. You can run `pnpm lint && pnpm type-check` before doing commit, or you should commit using `pnpm commit`. 

[CONTRIBUTING.md
](https://github.com/growupanand/ConvoForm/blob/main/CONTRIBUTING.md)

```
> convoform@0.9.1 type-check /home/growupanand/Development/repos/ConvoForm
> dotenv -- turbo run type-check

• Packages in scope: @convoform/api, @convoform/db, @convoform/eslint-config, @convoform/react, @convoform/tsconfig, @convoform/ui, @convoform/websocket-client, web, websocket-server
• Running type-check in 9 packages
• Remote caching disabled
@convoform/db:type-check: cache hit, replaying logs f26d41b23772526f
@convoform/db:type-check: 
@convoform/db:type-check: > @convoform/db@0.0.0 type-check /home/growupanand/Development/repos/ConvoForm/packages/db
@convoform/db:type-check: > tsc --noEmit
@convoform/db:type-check: 
@convoform/ui:type-check: cache hit, replaying logs 03ccf6224da36f4a
@convoform/ui:type-check: 
@convoform/ui:type-check: > @convoform/ui@0.0.0 type-check /home/growupanand/Development/repos/ConvoForm/packages/ui
@convoform/ui:type-check: > tsc --noEmit
@convoform/ui:type-check: 
@convoform/websocket-client:type-check: cache hit, replaying logs 21d107fc453bad6f
@convoform/websocket-client:type-check: 
@convoform/websocket-client:type-check: > @convoform/websocket-client@0.0.1 type-check /home/growupanand/Development/repos/ConvoForm/packages/websocket-client
@convoform/websocket-client:type-check: > tsc --noEmit
@convoform/websocket-client:type-check: 
@convoform/api:type-check: cache hit, replaying logs 85b4d6326e7b8d97
@convoform/api:type-check: 
@convoform/api:type-check: > @convoform/api@0.0.0 type-check /home/growupanand/Development/repos/ConvoForm/packages/api
@convoform/api:type-check: > tsc --noEmit
@convoform/api:type-check: 
@convoform/react:type-check: cache hit, replaying logs 80187d1d6873eb76
@convoform/react:type-check: 
@convoform/react:type-check: > @convoform/react@0.1.0 type-check /home/growupanand/Development/repos/ConvoForm/packages/react
@convoform/react:type-check: > tsc --noEmit
@convoform/react:type-check: 
web:type-check: cache miss, executing c1cf096793df2c24
web:type-check: 
web:type-check: > web@0.2.1 type-check /home/growupanand/Development/repos/ConvoForm/apps/web
web:type-check: > tsc --noEmit
web:type-check: 
web:type-check: src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:182:14 - error TS2345: Argument of type '(cs: State) => { removedFields: (Record<"id", string> | undefined)[]; isGeneratingAIField: boolean; }' is not assignable to parameter of type 'SetStateAction<State>'.
web:type-check:   Type '(cs: State) => { removedFields: (Record<"id", string> | undefined)[]; isGeneratingAIField: boolean; }' is not assignable to type '(prevState: State) => State'.
web:type-check:     Call signature return types '{ removedFields: (Record<"id", string> | undefined)[]; isGeneratingAIField: boolean; }' and 'State' are incompatible.
web:type-check:       The types of 'removedFields' are incompatible between these types.
web:type-check:         Type '(Record<"id", string> | undefined)[]' is not assignable to type 'Record<"id", string>[]'.
web:type-check:           Type 'Record<"id", string> | undefined' is not assignable to type 'Record<"id", string>'.
web:type-check:             Type 'undefined' is not assignable to type 'Record<"id", string>'.
web:type-check: 
web:type-check: 182     setState((cs) => ({
web:type-check:                  ~~~~~~~~~~
web:type-check: 183       ...cs,
web:type-check:     ~~~~~~~~~~~~
web:type-check: 184       removedFields: [...cs.removedFields, removedField],
web:type-check:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
web:type-check: 185     }));
web:type-check:     ~~~~~~
web:type-check: 
web:type-check: src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:192:29 - error TS2345: Argument of type 'Record<"id", string>' is not assignable to parameter of type '{ fieldName: string; } | { fieldName: string; }[]'.
web:type-check: 
web:type-check: 192       insert(fields.length, lastRemovedField);
web:type-check:                                 ~~~~~~~~~~~~~~~~
web:type-check: 
web:type-check: 
web:type-check: Found 2 errors in the same file, starting at: src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:182
web:type-check: 
web:type-check:  ELIFECYCLE  Command failed with exit code 2.
web:type-check: ERROR: command finished with error: command (/home/growupanand/Development/repos/ConvoForm/apps/web) /home/growupanand/.volta/bin/pnpm run type-check exited (1)
web#type-check: command (/home/growupanand/Development/repos/ConvoForm/apps/web) /home/growupanand/.volta/bin/pnpm run type-check exited (1)

 Tasks:    5 successful, 6 total
Cached:    5 cached, 6 total
  Time:    4.425s 
Failed:    web#type-check

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 1]
```diff
@@ -173,6 +176,23 @@ export function FormEditorCard({ form }: Readonly<Props>) {
...
+    }));
+  };
+
+  const handleUndoRemoveField = () => {
+    const lastRemovedField = removedFields.pop();
+    if (lastRemovedField) {
+      setState((cs) => ({ ...cs, removedFields }));
+      insert(fields.length, lastRemovedField);
+    }
+  };
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:194]: Check for type errors.

**Screenshot**
image

**Review by growupanand — CHANGES_REQUESTED** [review]

**Comment by Hemu21** [comment]
@growupanand  updated can you please check.

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 2]
```diff
@@ -67,7 +68,13 @@ export function FormEditorCard({ form }: Readonly<Props>) {
   });
   const { isGeneratingAIField } = state;
 
-  const formDefaultValues = form as FormSubmitDataSchema;
+  const formDefaultValues = {
+    ...form,
+    formFields: form.formFields.map((field) => ({
+      ...field,
+      isMarkedForRemoval: false,
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:75]: Instead of mutating the original object, let's do it this way.

1. Create a state  `removeFieldsIds` to store all formIds here which need to be removed on form submit

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 3]
```diff
@@ -116,11 +129,20 @@ export function FormEditorCard({ form }: Readonly<Props>) {
   });
   const isFormBusy = updateForm.isPending;
 
-  const onSubmit = (formData: FormSubmitDataSchema) =>
+  const onSubmit = (formData: FormSubmitDataSchema) => {
+    console.log("form data", formData);
+    const cleanedData = {
+      ...formData,
+      formFields: formData.formFields.filter(
+        (field) => field.isMarkedForRemoval != true,
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:137]: We can filter fields which are marked to remove by using `(field, index) => !removeFieldsIds.includes(fields[index]!.id),`

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 4]
```diff
@@ -138,7 +160,10 @@ export function FormEditorCard({ form }: Readonly<Props>) {
       });
       const responseJson = await response.json();
       const { fieldName } = responseJson;
-      append({ fieldName });
+      append({ fieldName, isMarkedForRemoval: false } as {
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:163]: You can remove `isMarkedForRemoval` now because we will use `removeFieldsIds` state for this.

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 5]
```diff
@@ -172,6 +197,15 @@ export function FormEditorCard({ form }: Readonly<Props>) {
...
   };
+  const toggleRemoveField = (index: number) => {
+    const field = fields[index];
+    if (field) {
+      update(index, {
+        ...field,
+        isMarkedForRemoval: !field.isMarkedForRemoval,
+      } as { fieldName: string; isMarkedForRemoval: boolean });
+    }
+  };
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:208]: Use below code:

```
  const toggleRemoveField = (
    fieldIndex: number,
    field: { fieldName: string; id: string },
  ) => {
    // Check if field is already marked for removal
    if (removeFieldsIds.includes(field.id)) {
      setState((cs) => ({
        ...cs,
        removeFieldsIds: removeFieldsIds.filter((id) => id !== field.id),
      }));
      return;
    }

    const fieldValue = formHook.getValues().formFields[fieldIndex]?.fieldName;
    // check if field value is empty then we can safely remove it instead of marking it for removal
    if (fieldValue === "") {
      // remove field
      remove(fieldIndex);
      return;
    }

    // mark field for removal
    setState((cs) => ({
      ...cs,
      removeFieldsIds: [...removeFieldsIds, field.id],
    }));
  };
```

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 6]
```diff
@@ -368,7 +400,9 @@ export function FormEditorCard({ form }: Readonly<Props>) {
                     <div className=" mt-2 flex gap-3 max-lg:flex-col lg:items-center">
                       <Button
                         variant="outline"
-                        onClick={() => append({ fieldName: "" })}
+                        onClick={() =>
+                          append({ fieldName: "", isMarkedForRemoval: false })
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:404]: revert this.

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 7]
```diff
@@ -340,22 +374,20 @@ export function FormEditorCard({ form }: Readonly<Props>) {
...
                                   variant="ghost"
-                                  disabled={
-                                    (index === 0 && fields.length === 1) ||
-                                    isGeneratingAIField ||
-                                    isFormBusy
-                                  }
-                                  onClick={() =>
-                                    fields.length != 1 && remove(index)
-                                  }
+                                  onClick={() => toggleRemoveField(index)}
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:382]: use this

`onClick={() => toggleRemoveField(index, item)}`

File: apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx [hunk 8]
```diff
@@ -340,22 +374,20 @@ export function FormEditorCard({ form }: Readonly<Props>) {
                                   onKeyDown={(e) =>
                                     handleFormFieldInputKeyDown(e, item)
                                   }
+                                  disabled={item.isMarkedForRemoval}
```
Comment (growupanand) [inline apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx:377]: create a small function in same file outside component for this like 

```
const  isFieldMarkedForRemoval = (id:string) => {
removeFieldsIds.includes(id)
}
```

**Review by growupanand — CHANGES_REQUESTED** [review]
Please check comments.

**Comment by Hemu21** [comment]
@growupanand updated can you please check it.

**Comment by growupanand** [comment]
@Hemu21 , Functionality-wise, it looks good to me; please check for type and lint errors.

image


Can you please do one little UX improvement, we can show a tooltip for the remove and undo field button so when user will hover the button they get clear message what the button will do. 

You can use this component from shadcn: https://ui.shadcn.com/docs/components/tooltip


After these changes, this is ready to merge.

**Comment by Hemu21** [comment]
@growupanand  updated can you please check
